export const styles = {
  container: { 
    width: '100vw', 
    height: '100vh', 
    fontFamily: '"Inter", sans-serif', 
    backgroundColor: '#f1f5f9', 
    overflow: 'hidden',
    position: 'relative'
  },
  customWatermarkBackground: {
    position: 'absolute',
    top: '-50%',
    left: '-50%',
    width: '200%',
    height: '200%',
    backgroundImage: 'url("/logo-smsmode.svg")',
    backgroundSize: '160px 160px',
    backgroundRepeat: 'repeat',
    transform: 'rotate(-25deg)',
    opacity: 0.18,
    filter: 'brightness(0) invert(1)',
    pointerEvents: 'none',
    zIndex: 0
  },
  nodeWrapper: {
    width: '410px',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    border: '1px solid #cbd5e1',
    padding: '20px',
    boxSizing: 'border-box',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.05), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    position: 'relative',
    transition: 'all 0.2s ease',
    zIndex: 1,
  },
  toolbar: {
    position: 'absolute',
    top: '-44px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#ffffff',
    border: '1px solid #cbd5e1',
    color: '#1e293b',
    padding: '6px 12px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    zIndex: 100,
    fontSize: '12px',
    whiteSpace: 'nowrap',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  styleMenu: {
    position: 'absolute',
    bottom: '45px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    padding: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
    zIndex: 120,
  },
  colorBox: { width: '20px', height: '20px', borderRadius: '4px', cursor: 'pointer', border: '1px solid rgba(0,0,0,0.1)' },
  linkPopup: {
    position: 'absolute',
    top: '-95px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#ffffff',
    padding: '10px',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    zIndex: 200,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)',
    width: '170px'
  },
  popupInput: { padding: '6px 8px', fontSize: '11px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none' },
  toolbarBtn: { background: 'none', border: 'none', color: '#475569', cursor: 'pointer', fontSize: '12px', fontWeight: '500', display: 'inline-flex', alignItems: 'center', gap: '4px' },
  nodeLabel: { fontSize: '11px', fontWeight: '700', color: '#64748b', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.05em', display: 'block' },
  editableArea: { 
    width: '100%', 
    minHeight: '65px', 
    maxHeight: '150px', 
    padding: '10px', 
    marginBottom: '12px', 
    boxSizing: 'border-box', 
    border: '1px solid #cbd5e1', 
    borderRadius: '10px', 
    fontSize: '13px', 
    outline: 'none', 
    lineHeight: '1.5', 
    backgroundColor: '#fff', 
    overflowY: 'auto', 
    whiteSpace: 'pre-wrap', 
    wordBreak: 'break-word',
    color: '#000000'
  },
  optionRow: { display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' },
  dragHandle: { display: 'flex', flexDirection: 'column', gap: '2px', userSelect: 'none' },
  sortBtn: { background: 'none', border: 'none', cursor: 'pointer', color: '#94a3b8', padding: '2px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  optionInput: { 
    flex: 1, 
    padding: '6px 12px', 
    border: '1px solid #cbd5e1', 
    borderRadius: '10px', 
    fontSize: '13px', 
    outline: 'none', 
    backgroundColor: '#fff', 
    maxWidth: '180px', 
    boxSizing: 'border-box',
    overflowX: 'auto',
    color: '#000000'
  },
  iconBtn: { background: 'none', border: 'none', cursor: 'pointer', padding: '4px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: '#64748b' },
  addOptionBtn: { width: '100%', padding: '12px', backgroundColor: '#f1f5f9', border: 'none', borderRadius: '9999px', cursor: 'pointer', fontSize: '12px', fontWeight: '600', color: '#475569', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '6px' },
  addChildBtn: {
    position: 'absolute',
    right: '-30px',
    top: '60%',
    transform: 'translateY(-50%)',
    width: '58px',
    height: '58px',
    borderRadius: '50%',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: '4px solid #fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    zIndex: 10,
    fontSize: '32px',
    fontWeight: 'bold',
    lineHeight: 1,
    paddingBottom: '2px'
  },
  overlayBL: { position: 'fixed', bottom: '24px', left: '24px', display: 'flex', flexDirection: 'column', gap: '12px', zIndex: 100, backgroundColor: '#fff', padding: '14px', borderRadius: '24px', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0', alignItems: 'center' },
  overlayBR: { position: 'fixed', bottom: '24px', right: '24px', display: 'flex', gap: '12px', zIndex: 100, backgroundColor: '#fff', padding: '14px', borderRadius: '24px', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0', alignItems: 'center' },
  overlayTR: { 
    position: 'fixed', 
    top: '24px', 
    right: '24px', 
    display: 'flex', 
    alignItems: 'center', 
    gap: '14px', 
    zIndex: 100, 
    backgroundColor: '#fff', 
    padding: '10px 20px', 
    borderRadius: '9999px', 
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.05)', 
    border: '1px solid #e2e8f0' 
  },
  overlayTL: {
    position: 'fixed',
    top: '24px',
    left: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    zIndex: 100,
    backgroundColor: 'transparent',
    padding: '0px',
    borderRadius: '0px',
    boxShadow: 'none',
    border: 'none'
  },
  sendBtn: {
    padding: '12px 24px',
    backgroundColor: '#094776',
    border: 'none',
    borderRadius: '9999px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
    color: '#ffffff',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px'
  },
  logoCircle: {
    width: '42px',
    height: '42px',
    borderRadius: '50%',
    backgroundColor: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    border: '2px solid #cbd5e1'
  },
  usernameInput: {
    border: 'none',
    outline: 'none',
    fontSize: '13px',
    fontWeight: '600',
    color: '#1e293b',
    backgroundColor: 'transparent',
    width: '130px',
    padding: '0px',
    borderBottom: '1px dashed #cbd5e1'
  },
  controlBtn: { padding: '8px 16px', backgroundColor: '#fff', border: '1px solid #e2e8f0', borderRadius: '9999px', cursor: 'pointer', fontSize: '13px', fontWeight: '500', color: '#1e293b', display: 'inline-flex', alignItems: 'center', gap: '6px' },
  circularControlBtn: { width: '40px', height: '40px', borderRadius: '50%', backgroundColor: '#fff', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#1e293b', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', padding: 0 },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(15, 23, 42, 0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, backdropFilter: 'blur(4px)' },
  modal: { backgroundColor: '#fff', padding: '28px', borderRadius: '24px', maxWidth: '440px', width: '100%', boxSizing: 'border-box', textAlign: 'center', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)' },
  modalTitle: { marginTop: 0, fontSize: '16px', color: '#0f172a', fontWeight: '600', lineHeight: '1.5' },
  modalActions: { display: 'flex', justifyContent: 'center', gap: '14px', marginTop: '24px' },
  dropdownMenu: { position: 'absolute', top: '100%', right: '0', backgroundColor: '#fff', color: '#1e293b', border: '1px solid #e2e8f0', borderRadius: '12px', listStyle: 'none', padding: '6px 0', margin: '4px 0 0 0', minWidth: '150px', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)', zIndex: 120 },
  dropdownItem: { padding: '8px 14px', cursor: 'pointer', fontSize: '13px', textAlign: 'left', display: 'flex', alignItems: 'center', gap: '8px' },
};